[package]
name = "arf-strings"
version = "0.3.1-alpha.0"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
description = "Encoding and decoding for ARF strings"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
documentation = "https://docs.rs/arf-strings"
repository = "https://github.com/bytecodealliance/arf-strings"
exclude = ["/.github"]

[dependencies]

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.80" # for libc::EILSEQ

[badges]
maintenance = { status = "actively-developed" }
